### ISSUE TITLE
Question about the results of PRM and ORM

### ISSUE THREAD

**Issue by HillZhang1999** [Edward-Sun/easy-to-hard#1]
Dear Authors,

Firstly, I would like to express my appreciation for this outstanding work.

Upon reviewing your results, particularly those illustrated in Figures 8 and 9, I observed something intriguing. In the context of the findings presented in the original PRM800k papers, it was clear that PRM considerably outperformed ORM. However, based on the results you've shared, PRM and ORM appear to perform on a par with each other.

Could you please provide further insight into this discrepancy?

**Comment by Edward-Sun** [comment]
Hi Yue,

Thanks for the great question. First, I would like to point out that research about comparing ORM and PRM is still quite empirical, so it may differ on different models and training algorithms. For example, the original PRM800K paper uses a Minerva-finetuned GPT-4 base model, while we only uses Llemma-7b and Llemma-34b. We also find that best-of-n does not outperforms majority voting, which deviated from PRM800K's conclusion.

Secondly, in our experiments, we found that ORM and PRM reward modeling data are complimentary. For example, ORM seems to focus more on the evaluation of later steps in a solution, while PRM checks each step or may have higher accuracy on earlier steps. This is the main motivation that leads us to propose OPRM to combine their strengthes.
