### ISSUE TITLE
How do I convert the PPO trained model (.pt) into hf format ?

### ISSUE THREAD

**Issue by supermancmk** [Edward-Sun/easy-to-hard#10]
How do I convert the PPO trained model (.pt) into hf format?

I tried to use this file to convert using.  The following command:

```shell

python scripts/convert_checkpoint_to_hf.py \
    --tp_ckpt_name xxxx/path_to_ppo_model \
    --tokenizer_name EleutherAI/llemma_7b \
    --pretrain_name EleutherAI/llemma_7b \
    --save_name_hf xxxx/path_to_save

``` 

But I got the following error:

```shell
ValueError: Invalid key: tok_embeddings.weight
``` 

Also,  can you provide the command to evaluate MATH?

**Comment by Edward-Sun** [comment]
Which line is the error reported?

Also, I'm not sure `path_to_ppo_model` should contain the tok_embeddings since we made them frozen in this framework.
