### ISSUE TITLE
readme for data

### ISSUE THREAD

**Issue by rguo12** [Edward-Sun/easy-to-hard#2]
Dear authors,

Thanks for sharing the code. I wonder if you can update the data/readme.md for instructions to prepare the data.

Best regards,

RC

**Comment by Zjshadow** [comment]
The same request as you.

**Comment by Edward-Sun** [comment]
Hi @rguo12 @Zjshadow 

Sorry for the late reply. I was working on some ICML rebuttals. The instructions are updated. Please have a look!

https://github.com/Edward-Sun/easy-to-hard/tree/main/data

Thanks,
Zhiqing
