### ISSUE TITLE
Question about Paper: Is it possible to combine SFT and reward model?

### ISSUE THREAD

**Issue by Site1997** [Edward-Sun/easy-to-hard#8]
Dear authors,

I learned this paper in SIGIR 2024, presented by Prof. Yang. I'm impressed, and thank you for this brilliant idea!

For my education,
 - The Easy-to-Hard **SFT model** is fine-tuned based on _problems_ and _solutions_.
 - The Easy-to-Hard **Reward model** is fine-tuned on _solutions_ and their _process labels_.

I feel like the analogy is similar to policy model + reward model. Given that now we have DPO method, do you think it's possible fine-tune **one single model** based on _problems_, _solution_, and _process labels_, in which the model learns to generate the candidate answer and verify it inherently?

**Comment by Edward-Sun** [comment]
Good question. The main finding of our research is that the reward model generalizes better than the SFT model. So how well does an offline RL model generalize? I think this question is under exploration.
